# Generated by Django 4.2.4 on 2023-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_games_studio_workers_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
