# Generated by Django 4.2.4 on 2023-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_playerapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerapi',
            name='name_player',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='playerapi',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
