# Generated by Django 4.2.4 on 2023-08-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_playerapi_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='name',
            new_name='nameAPI',
        ),
    ]
