# Generated by Django 4.2.4 on 2023-08-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_name_studio_nameapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='nameAPI',
            new_name='name',
        ),
    ]
