# Generated by Django 4.2.4 on 2023-08-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_rename_name_playerapi_nameapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerapi',
            name='name_player',
            field=models.CharField(default='fohgot', max_length=255),
        ),
    ]
