# Generated by Django 4.2.4 on 2023-08-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_playerapi_name_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='studios',
            field=models.ManyToManyField(to='games.studio'),
        ),
    ]
