# Generated by Django 4.2.4 on 2023-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_genre_games_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('game', models.ManyToManyField(related_name='Коллекция', to='games.games')),
            ],
        ),
    ]
