# Generated by Django 4.2.4 on 2023-08-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_gamecollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='genres',
        ),
        migrations.AddField(
            model_name='games',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.genre'),
        ),
    ]
